
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hasil
 */
public class issuerecord extends javax.swing.JDialog {
String bname,pname,id1;


    /**
     * Creates new form issuerecord
     */
    public issuerecord(String a,String b, String i) {
        
        initComponents();
        bname=a;
        pname=b;
        id1=i;
        this.setLocationRelativeTo(null);
        this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
         addDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        last = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        issuedate = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        returndate = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        String colHeader []= new String []{"ID","First Name","Last Name","Phone No.","Address","Faculty",
            "Course","Semester"
        };
        dtm = new DefaultTableModel(0,0);
        dtm.setColumnIdentifiers(colHeader);
        tbl1 = new javax.swing.JTable();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Issue Record");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });
        last.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastKeyReleased(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel5.setText("Book Name");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel6.setText("Publisher");

        jLabel3.setText("Last Name");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("No result Found!!!");

        bookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknameActionPerformed(evt);
            }
        });

        jLabel7.setText("Issued Date:");

        issuedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedateActionPerformed(evt);
            }
        });

        jLabel4.setText("Student Name");

        jLabel8.setText("Returning Date:");

        first.setSelectionColor(new java.awt.Color(255, 255, 255));
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });
        first.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstKeyReleased(evt);
            }
        });

        returndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returndateActionPerformed(evt);
            }
        });

        tbl1.setModel(dtm);
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(first, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisher)
                    .addComponent(bookname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(back))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastActionPerformed

    private void lastKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_lastKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //db_operation1 dbopt = new db_operation1();
        //        ResultSet rs = dbopt.searchStudentInformation(search.getText().toString());
        //        rs1 = rs;
        // dtm.setRowCount(0);
        //        try {
            //
            //
            //            while (rs.next()) {
                //
                //                String id = rs.getString(1); //String  id= rs.getString("ID");
                //                String bname = rs.getString(2); //String fname=rs.getString("FirstName");
                //                String edition = rs.getString(3);
                //                String publisher = rs.getString(4);
                //                String qnty = rs.getString(5);
                //
                //
                //                Vector<String> v = new Vector<String>();
                //                v.add(id);
                //                v.add(bname);
                //                v.add(edition);
                //                v.add(publisher);
                //                v.add(qnty);
                //
                //                dtm.addRow(v);
                //
                //                jLabel2.setVisible(false);
                //
                //            }
            //
            //        } catch (SQLException ex) {
            //            System.out.println("Error in addDataToTable" + ex);
            //        }
        //        if (dtm.getRowCount() == 0) {
            //            jLabel2.setVisible(true);
            //
            //        } else {
            //           jLabel2.setVisible(false);
            //
            //        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        view_n_search v1= new view_n_search(new javax.swing.JFrame(), true);
        v1.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void booknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booknameActionPerformed

    private void issuedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedateActionPerformed

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_firstActionPerformed

    private void firstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstKeyReleased
String name=this.first.getText();

        db_operation dbopt=new db_operation();
        ResultSet rs=dbopt.searchBookInformation(name);
     
 dtm.setRowCount(0);
        try {
            System.out.println("assa");


            while (rs.next()) {
                System.out.println("add");
                String id = rs.getString(1); //String  id= rs.getString("ID");
                String firstname = rs.getString(2); //String fname=rs.getString("FirstName");
                String lastname = rs.getString(3);
               String  phone= rs.getString(4);
                                String  address= rs.getString(5);
                
                
                                 String  faculty= rs.getString(6);
                                  String  course= rs.getString(7);
                                    String  sem= rs.getString(8);
                

                Vector<String> v = new Vector<String>();
                v.add(id);
               v.add(firstname);
               v.add(lastname);
               v.add(phone);
                                  v.add(address);
                                  v.add(faculty);
                                  v.add(course);
                
                                  v.add(sem);
               
                dtm.addRow(v);

                jLabel2.setVisible(false);

            }

        } catch (SQLException ex) {
            System.out.println("Error in addDataToTable" + ex);
        }
        if (dtm.getRowCount() == 0) {
            jLabel2.setVisible(true);
           
        } else {
           jLabel2.setVisible(false);

        }   
    }//GEN-LAST:event_firstKeyReleased

    private void returndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returndateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returndateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        this.setLocation(x, y);  
        jLabel2.setVisible(false);   
 bookname.setText(bname);
 publisher.setText(pname);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    try {
        Date  d = returndate.getDate(); // not in sql..... import in util
        DateFormat df= new SimpleDateFormat("yyyy-MM-dd");
        //reltn maintain for date and dateformat
        String returnda=df.format(d);
        
        Date  d1 = issuedate.getDate(); // not in sql..... import in util
        DateFormat df1= new SimpleDateFormat("yyyy-MM-dd");
        //reltn maintain for date and dateformat
        String issueda=df1.format(d1);
        String id3=tbl1.getModel().getValueAt(tbl1.getSelectedRow(), 0).toString();
        
        db_operation3 db = new db_operation3();
        db.addIssueInfo(issueda,returnda,id3,id1);
        
         JOptionPane.showMessageDialog(this, "Issue added successfully");
        // TODO add your handling code here:
    } catch (ParseException ex) {
        Logger.getLogger(issuerecord.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_submitActionPerformed

    private void tbl1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseReleased
if (evt.getClickCount() == 1) {System.out.println("Hello");
        //if (evt.getClickCount() == 2) {
           db_operation1 dbopt=new db_operation1();
          String a= tbl1.getModel().getValueAt(tbl1.getSelectedRow(), 1).toString();
         // this.setVisible();
          first.setText("");
           first.setText(a);
            String b= tbl1.getModel().getValueAt(tbl1.getSelectedRow(), 2).toString();
         // this.setVisible();
          last.setText("");
           last.setText(b);
                   // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseReleased

//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(issuerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(issuerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(issuerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(issuerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                issuerecord dialog = new issuerecord(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//     }   });
//    }

    }
    public void addDataToTable() {
        try {
            db_operation1 dbopt=new db_operation1();
            ResultSet rs=dbopt.viewAllStudentInformation();
            
            while(rs.next()){
              
                String  id= rs.getString(1); //String  id= rs.getString("ID");
                String  fname= rs.getString(2); //String fname=rs.getString("FirstName");
                String  lname= rs.getString(3);
                 String  phone= rs.getString(4);
                String  address= rs.getString(5);


                 String  faculty= rs.getString(6);
                  String  course= rs.getString(7);
                    String  sem= rs.getString(8);
                  Vector<String> v=new Vector<String>();
                  v.add(id);
                  v.add(fname);
                  v.add(lname);
                  v.add(phone);
                  v.add(address);
                  v.add(faculty);
                  v.add(course);
                  
                  v.add(sem);
                  dtm.addRow(v); 
          
                
            }   } catch (SQLException ex) {
            Logger.getLogger(view_n_search.class.getName()).log(Level.SEVERE, null, ex);
        }
}    
    DefaultTableModel dtm=null; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bookname;
    private javax.swing.JTextField first;
    private org.jdesktop.swingx.JXDatePicker issuedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last;
    private javax.swing.JTextField publisher;
    private org.jdesktop.swingx.JXDatePicker returndate;
    private javax.swing.JButton submit;
    private javax.swing.JTable tbl1;
    // End of variables declaration//GEN-END:variables
}
